export const HOME_ASSISTANT_ENTITY_DOMAINS: { id: string; label: string }[] = [
    { id: "air_quality", label: "Air Quality" },
    { id: "alarm_control_panel", label: "Alarm Control Panel" },
    { id: "assist_satellite", label: "Assist Satellite" },
    { id: "automation", label: "Automation" },
    { id: "binary_sensor", label: "Binary Sensor" },
    { id: "button", label: "Button" },
    { id: "calendar", label: "Calendar" },
    { id: "camera", label: "Camera" },
    { id: "climate", label: "Climate" },
    { id: "conversation", label: "Conversation" },
    { id: "cover", label: "Cover" },
    { id: "date", label: "Date" },
    { id: "datetime", label: "Date/Time" },
    { id: "device_tracker", label: "Device Tracker" },
    { id: "event", label: "Event" },
    { id: "fan", label: "Fan" },
    { id: "geo_location", label: "Geolocation" },
    { id: "group", label: "Group" },
    { id: "humidifier", label: "Humidifier" },
    { id: "image", label: "Image" },
    { id: "image_processing", label: "Image Processing" },
    { id: "input_boolean", label: "Input Boolean" },
    { id: "input_datetime", label: "Input Date/Time" },
    { id: "input_number", label: "Input Number" },
    { id: "input_select", label: "Input Select" },
    { id: "input_text", label: "Input Text" },
    { id: "lawn_mower", label: "Lawn Mower" },
    { id: "light", label: "Light" },
    { id: "lock", label: "Lock" },
    { id: "media_player", label: "Media Player" },
    { id: "number", label: "Number" },
    { id: "person", label: "Person" },
    { id: "persistent_notification", label: "Persistent Notification" },
    { id: "remote", label: "Remote" },
    { id: "scene", label: "Scene" },
    { id: "script", label: "Script" },
    { id: "select", label: "Select" },
    { id: "sensor", label: "Sensor" },
    { id: "siren", label: "Siren" },
    { id: "stt", label: "Speech-to-Text (STT)" },
    { id: "sun", label: "Sun" },
    { id: "switch", label: "Switch" },
    { id: "tag", label: "Tag" },
    { id: "text", label: "Text" },
    { id: "time", label: "Time" },
    { id: "todo", label: "To-Do List" },
    { id: "tts", label: "Text-to-Speech (TTS)" },
    { id: "timer", label: "Timer" },
    { id: "update", label: "Update" },
    { id: "valve", label: "Valve" },
    { id: "vacuum", label: "Vacuum" },
    { id: "wake_word", label: "Wake Word Detection" },
    { id: "water_heater", label: "Water Heater" },
    { id: "weather", label: "Weather" },
    { id: "zone", label: "Zone" }
];